[package]
name = "stickykeys_toggle"
version = "1.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }

windows = { version = "0.62", features = ["Win32_UI_WindowsAndMessaging", "Win32_UI_Accessibility"] }
rodio = "0.21"
pretty_env_logger = "0.5"