[package]
name = "stickykeys_toggle"
version = "1.0.0"
edition = "2024"

[dependencies]
windows = { version = "0.61", features = ["Win32_UI_WindowsAndMessaging", "Win32_UI_Accessibility"] }
rodio = "0.21"

[profile.release]
lto = "fat"
panic = "abort"
strip = "symbols"