[package]
name = "ralsei-quiz-tracker"
version = "1.0.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pretty_env_logger = "0.5"
win-hotkeys = "0.5"
crossbeam = "0.8"